// Generated by CoffeeScript 1.8.0
(function() {
  var StringUtil, basic, d;

  StringUtil = typeof require !== "undefined" && require !== null ? require('../coffee/string').StringUtil : this.StringUtil;

  basic = function() {
    return StringUtil.pyformat('{0}, {1:^10}, {2:#b}, {4:>3}, {:*<3}, {:0^5}', 1, 2, 3, 4, 5, 6);
  };

  d = Date.now();

  console.log("" + (basic()) + "\nTime: " + (Date.now() - d) + "ms");

}).call(this);
